apiVersion: v1
kind: Secret
metadata:
  name: {{ template "project.fullname" . }}
data:

  {{- $root := . }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
