# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# fullnameOverride: blankcrm
replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: sw-secret
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets: 
#   ACCESSKEYID: "R3LNFRKWMAC4OCCRICS5"
#   SECRETACCESSKEY: "YPyyTdxs+lZMQEtYIDRK9lkIzjJrCKXinE3OfKEfc7k"
#   BUCKETNAME: "pdftemplar"
#   SERVICEURL: "https://fra1.digitaloceanspaces.com"
#   BLOBURL: "https://pdftemplar.fra1.digitaloceanspaces.com"
#   ELASTIC_NAME: "pdftemplar"
#   ELASTIC_URL: "https://a3cbf8539c4c490996689ab5d66f082f.eu-west-1.aws.found.io:9243"
#   ELASTIC_USER: "elastic"
#   ELASTIC_PASSWORD: "CVVTSQOhIbf3UAAuIdiSPNPP"
#   REACT_APP_BUILD: "20w13a"
environment: development

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


global:





